### ISSUE TITLE
Integrating CKFinder with CKEditor

### ISSUE THREAD

**Issue by ericbrown** [greyli/flask-ckeditor#1]
This is a great approach for implementing ckeditor. Thanks for the effort.   Have you looked at integrating CKFinder into CKEditor? I'm looking at this now but not quite sure how to go about it.

**Comment by greyli** [comment]
It seems not difficult, I will try to implement it in the next release in next week.

**Comment by ericbrown** [comment]
Thanks. Looking forward to it. I'll test it out and provide any feedback.

**Comment by greyli** [comment]
That's great, thank you!

**Comment by greyli** [comment]
Sorry for the delay, I'm quite busy these days. I try to implement the integrate of CKFider, but find out the CKFider currently doesn't support Python. However, the current code can be hooked to other file browsers with configuration key `CKEDITOR_FILE_BROWSER_URL`, you may give it a try.

**Comment by greyli** [comment]
Besides, you can pass custom url to `load()` methods now, which means you can bulid your own CKEditor with [CKEditor Builder](https://ckeditor.com/cke4/builder), you can choose a third party file browser as [add-ons](https://ckeditor.com/cke4/addons/plugins/all/).
