### ISSUE TITLE
How install plugins ?

### ISSUE THREAD

**Issue by gnoo0** [greyli/flask-ckeditor#11]
Hi, i need plugins in the  text editor but i don't now how add them...

Plugins i need, font color, font family, etc...

I m a beginner, i need clear examples... step by step.

Thank you !

**Comment by greyli** [comment]
1. Go to https://ckeditor.com/cke4/builder, add the plugins you need, then build and download the package.
2. Unzip the package and put it under the `static/`.
3. Link the `ckeditor.js` inside of the package folder in the template.

**Comment by greyli** [comment]
Try to load the file like this:
```html
 Your Form Here
 {{ ckeditor.load(custom_url=url_for('static', filename='ckeditor/ckeditor.js')) }}
 {{ ckeditor.config(name='content') }}
```

**Comment by gnoo0** [comment]
is not working...

**Comment by greyli** [comment]
What's the file structure of your static folder?

**Comment by gnoo0** [comment]
![captura de ecra_2018-09-12_10-46-04](https://user-images.githubusercontent.com/43119920/45416995-10907200-b679-11e8-9ee2-60b449ee562c.png)

![captura de ecra_2018-09-12_10-46-55](https://user-images.githubusercontent.com/43119920/45417060-3453b800-b679-11e8-869c-dbf75ffc96cd.png)

**Comment by greyli** [comment]
It seems that you still use the built-in resources. Please provide the full template code.

**Comment by gnoo0** [comment]
![captura de ecra_2018-09-12_10-52-08](https://user-images.githubusercontent.com/43119920/45417366-ebe8ca00-b679-11e8-98c8-74be565d025a.png)

**Comment by greyli** [comment]
Remove `{{ ckeditor.load() }}`.

**Comment by gnoo0** [comment]
Yup ... that works...
Thank you for your help, you are doing a great with this project...
Thumbs up ....

**Comment by graceyudhaaa** [comment]
> 1. Go to https://ckeditor.com/cke4/builder, add the plugins you need, then build and download the package.
> 2. Unzip the package and put it under the `static/`.
> 3. Link the `ckeditor.js` inside of the package folder in the template.

Hey i know this is an old issue, but in the documentation extra plugins are supposed to be listed in the config under CKEDITOR_EXTRA_PLUGINS. does it still apply in this case?

**Comment by graceyudhaaa** [comment]
that clear things up, thank you
