### ISSUE TITLE
how remove plugin from basic example 

### ISSUE THREAD

**Issue by ghost** [greyli/flask-ckeditor#12]
Is possible remove the source plugin from your example ?

![captura de ecra_2018-09-18_12-20-15](https://user-images.githubusercontent.com/43119920/45684129-42a04900-bb3d-11e8-9552-2b2d7522a653.png)

[https://github.com/greyli/flask-ckeditor/tree/master/examples/basic](url)

**Comment by greyli** [comment]
You can build your own CKEditor package to remove this plugin.

**Comment by gnoo0** [comment]
So i should ask this different... how can i add two different packages  to the same app ? 
I created a package and i add it to static folder, and i tried to change the name of files but didn't work.

**Comment by gnoo0** [comment]
yup you are right sorry about that :)
