### ISSUE TITLE
The example about how to use Markdown in the Flask-CKEditor is Missing

### ISSUE THREAD

**Issue by meizhaohui** [greyli/flask-ckeditor#13]
- examples/markdown: This example demonstrate how to use add Markdown plugin.

this example is **Missing**

I use the **app.config['CKEDITOR_EXTRA_PLUGINS'] = ['markdown']**  and **app.config['CKEDITOR_ENABLE_MARKDOWN'] = True** will lead the CKEditor shows the "Markdown" button. But when I click it ,the input text will be clear. And then can't input anything. Please help. Thanks.

![input](https://user-images.githubusercontent.com/18098773/48548624-6814bd80-e908-11e8-91a4-75221afa9a43.png)
**can't display like this:**
![default](https://user-images.githubusercontent.com/18098773/48548638-71058f00-e908-11e8-8bf5-b01e8b229ef6.png)

**Comment by greyli** [comment]
This feature was removed since the markdown plugin is unmaintained and not work with CKEditor > 4.6. The documentation needs to update.
