### ISSUE TITLE
代码高亮插件无法选择代码语言

### ISSUE THREAD

**Issue by chenzanyu** [greyli/flask-ckeditor#15]
![qq 20181226152724](https://user-images.githubusercontent.com/35652064/50436901-d181e600-0922-11e9-9f68-bab8c3e73179.png)

**Comment by greyli** [comment]
在本地无法复现，请提供相关代码。

**Comment by greyli** [comment]
I'll close this issue for now. Please feel free to comment further or re-open this issue if you wish.
