### ISSUE TITLE
pass config in flask admin

### ISSUE THREAD

**Issue by git-bone** [greyli/flask-ckeditor#17]
hi,

I installed ckeditor with plugin 'wordcount'. As far as I understand the documentation, it should be possible to pass a variable 'maxCharCount' . Any chance on support to get that working? I tried all kinds of combinations like in this syntax  {{ ckeditor.config( ... )  }}. I cannot get it to work. 

It does work however, if I hardcode the maxCharCount in the plugin.js file, but that would mean I have to give all textarea fields the same value.

kind regards

**Comment by git-bone** [comment]
I found that this is at least something that seems to work.

    {{ ckeditor.load(custom_url = url_for('static', filename='ckeditor/ckeditor.js')) }}
    <script type="text/javascript">
        CKEDITOR.replace( "question", {extraPlugins : 'wordcount', wordcount : {maxCharCount: 2000}});
    </script>

**Comment by greyli** [comment]
You may need to do something like this (not test yet):

app.py:
```py
app.config['CKEDITOR_EXTRA_PLUGINS'] = ['wordcount']
```
In template:
```py
{{ ckeditor.config(custom_config="wordcount : {maxCharCount: 2000}") }}
```

**Comment by git-bone** [comment]
That works, many thanks! 

I already had app config with extra plugins, without that the plugin doesn't even show. However, I didn't know I could use name and custom config in the same line. 
I was using 2 separate lines:

{{ ckeditor.config(name='question') }}
{{ ckeditor.config(custom_config="wordcount : {maxCharCount: 2000}") }} ) and all kinds of variations on that. Which all result in a javascript with name "ckeditor" instead of the actual field name.
