### ISSUE TITLE
关于图片上传中样例一些疑惑

### ISSUE THREAD

**Issue by yinzhipeng123** [greyli/flask-ckeditor#20]
examples/image-upload/目录下中的app.py中的代码
对于这句代码app.config['UPLOADED_PATH'] = os.path.join(basedir, 'uploads')，不太理解，请问哪里有资料可以查阅

**Comment by greyli** [comment]
这一行是在定义上传路径（也就是文件被上传到哪个文件路径下），扩展本身并没有具体要求。你可以随便定义，这里把上传的目标文件夹定义为项目根目录（basedir）下的 uploads 文件夹。

如果你不清楚的是 os.path 相关 API，可以参考 [Python 文档](https://docs.python.org/2/library/os.path.html)。
