### ISSUE TITLE
示例代码basic项目中有XSS

### ISSUE THREAD

**Issue by wyzzoo** [greyli/flask-ckeditor#21]
示例代码basic项目中有XSS漏洞,对于示例代码本身肯定是没有实际影响,但是如果有小朋友也没搞明白就直接拿去用到生产环境的代码就很危险了。

**Comment by greyli** [comment]
具体说说？我没看出来在哪里……

**Comment by wyzzoo** [comment]
ckeditor中的数据没有经过任何处理就直接展示到页面上了，如果这些数据里有<script>alert(1)</script>这样的javascript代码，也就会造成XSS了。

例如
![image](https://user-images.githubusercontent.com/29711087/68524213-e67b2400-02fe-11ea-9bb6-b46d7e22a2f8.png)

**Comment by greyli** [comment]
IMO，实际是不会造成 XSS 的，因为有两层过滤：
- CKEditor 在保存输入内容的时候会对 JS 代码进行转义。
- 调用 `render_template()` 在渲染变量内容的时候也会对 HTML 代码进行转义。

**Comment by wyzzoo** [comment]
嗯 反正过滤一下CKEditor POST 过来的数据就好了。

**Comment by 99Kies** [comment]
如何把demo中工具栏上的源码按钮去掉呢？

**Comment by greyli** [comment]
Tips [added ](https://github.com/greyli/flask-ckeditor/commit/151efa12a82030f8a0a6bd5387a8fad0413f919d)in example applications.
