### ISSUE TITLE
please add flask admin image upload example

### ISSUE THREAD

**Issue by bekab95** [greyli/flask-ckeditor#24]
Upload tab does not appear in flask admin and please add full example with upload in flask admin

**Comment by greyli** [comment]
Example added: https://github.com/greyli/flask-ckeditor/tree/master/examples/flask-admin-upload

**Comment by greyli** [comment]
IMO, you may forget to call `ckeditor.load()` [in the template](https://github.com/greyli/flask-ckeditor/blob/master/examples/flask-admin-upload/templates/edit.html#L7) after set config variable in Python script.
