### ISSUE TITLE
HTTP error occurred during file upload (error status: 400)

### ISSUE THREAD

**Issue by bekab95** [greyli/flask-ckeditor#26]
Can not upload image everything is as in example

**Comment by ufo911** [comment]
As I found the problem is in CSRF and can not attach CSRF token by $.ajaxsetup

**Comment by greyli** [comment]
Which example application are you using? If you want to enable CSRF protection, you have to uncomment line 15, line 23 and line 29 in [image-upload](https://github.com/greyli/flask-ckeditor/blob/master/examples/image-upload/app.py) example.

**Comment by ufo911** [comment]
Thanks but it is not working in flask admin

**Comment by ufo911** [comment]
Please try a minimal app and flask admin together and see if CSRF is problem

**Comment by greyli** [comment]
OK, I will try to add an example for Flask-Admin with image upload.

**Comment by greyli** [comment]
Example app added [here](https://github.com/greyli/flask-ckeditor/tree/master/examples/flask-admin-upload), you can uncomment the related 3 lines in app.py to enable CSRF protection.

**Comment by AimanMRT** [comment]
![Untitled](https://user-images.githubusercontent.com/85171576/148026763-5c5f15f7-3e28-4d6e-ab3b-ef3ee5a8ae9a.png)
this is same problem??

**Comment by Ashwinch** [comment]
> AimanMRT

Were you able to find resolution for this, I am facing the same issue.
