### ISSUE TITLE
The "Codesnippet" plugin crashes ckeditor with pkg_type= 'basic'

### ISSUE THREAD

**Issue by AlertRED** [greyli/flask-ckeditor#29]
你好！
If I install a theme and add a plugin for the code:
```
class Config(object):
    CKEDITOR_PKG_TYPE = 'basic'
    CKEDITOR_ENABLE_CODESNIPPET = True
```
then in this case I get this error:
![image](https://user-images.githubusercontent.com/15695000/71765601-e465c800-2f31-11ea-874e-dad10ddb4ff9.png)

With _**CKEDITOR_PKG_TYPE = 'standart'**_ and _**'full'**_ all right.

![image](https://user-images.githubusercontent.com/15695000/71765798-8c2fc580-2f33-11ea-8360-ef30b919729d.png)

**Comment by greyli** [comment]
Hi, it seems that the Code snippet plugin relay on some plugins that is not included in basic package preset (i.e. [Line Utilities](https://ckeditor.com/cke4/addon/lineutils) and [Widget Selection](https://ckeditor.com/cke4/addon/widgetselection)). You can try to [build your own CKEdtior ](https://ckeditor.com/cke4/builder)basic package to include all the required plugins.

**Comment by rpmzandwijk** [comment]
On the other hand, the Code Snippet plugin is added by us, the package maintainers. So it would make sense that we also include the required plugins.

**Comment by rpmzandwijk** [comment]
We need to see more code to solve this, @AlertRED.

**Comment by rpmzandwijk** [comment]
@AlertRED we are going to include the Line Utilities and Widget Selection plugins in the basic package, to make the code snippet plugin work out of the box when using the basic package. It will be in the 0.4.4 release, which should be out soon.

**Comment by greyli** [comment]
The 0.4.4 version was released on Apr 27, 2020, please upgrade to fix this issue:

```
pip install -U flask-ckeditor
```
