### ISSUE TITLE
How to use custom built ckeditor?

### ISSUE THREAD

**Issue by senaps** [greyli/flask-ckeditor#3]
we have an option to build the ckeditor as we like it. but how would we be able to use that version with this?

**Comment by greyli** [comment]
Assuming your ckeditor resource package was placed at `/yourapp/static/ckeditor`, you can use `custom_url` in `load()`:
```python
<head>
{{ ckeditor.load(custom_url=url_for('static', filename='ckeditor/ckeditor.js')) }}
</head>
```

**Comment by senaps** [comment]
i tried it and it worked. thanks.

**Comment by greyli** [comment]
:)
