### ISSUE TITLE
CKEditor disappears when enable highlight.js

### ISSUE THREAD

**Issue by samzhangjy** [greyli/flask-ckeditor#30]
Hello!
I'm using flask-ckeditor==0.4.3, and when I enabled `CKEDITOR_ENABLE_CODESNIPPET = True
`, the editor disappears. But when not enable that, the editor can show up normally.

I also checked the console in the browser, and I got the following error:
`Error: [CKEDITOR.resourceManager.load] Resource name "codesnippet" was not found at "http://cdn.ckeditor.com/4.9.2/standard/plugins/codesnippet/plugin.js?t=I3I8".`

How can I solve this? Thank you!

**Comment by greyli** [comment]
Hi, sorry for the later response. Although Code Snippet is one of the CKEditor preset plugins,  but it not available on the [CKEditor CDN](https://ckeditor.com/cke4/presets-all). You have to load it from the local:
```html
{{ ckeditor.load() }}
{{ ckeditor.config(name='body') }}
<script>
    // Enable local "codesnippet" plugin from /ckeditor/static/standard/plugins/codesnippet/ path.
    CKEDITOR.plugins.addExternal( 'codesnippet', '/ckeditor/static/standard/plugins/codesnippet/', 'plugin.js' );
</script>
```

**Comment by samzhangjy** [comment]
Oh, now I got it. I will try it later, thanks a lot!
