### ISSUE TITLE
请问FLASK-Ckeditor怎么实现保存草稿功能？

### ISSUE THREAD

**Issue by Cyberbolt** [greyli/flask-ckeditor#33]
如果文章没写完，欲保存草稿，使用FLASK-Ckeditor怎么实现呢

**Comment by greyli** [comment]
这个需要你自己实现相关逻辑。因为和这个项目本身的代码无关，请把问题发到其他问答平台，或是这个 [Flask 论坛](https://discuss.helloflask.com)。
