### ISSUE TITLE
Package description not very descriptive

### ISSUE THREAD

**Issue by rpmzandwijk** [greyli/flask-ckeditor#38]
@greyli. I noticed that as of version 0.4.2, the package description (in setup.py) changed. Before version 0.4.2, it was pretty descriptive, but since then, it is not.

Was that change made on purpose?

Probably needless to say is that the description is used on PyPi, so people looking at the package on PyPi might not understand the function (and coolness!) of it.

**Comment by greyli** [comment]
At the moment, PyPI just starts to support render Markdown for the project description, but then something goes wrong about it and I can't figure out the reason at that time, so I just remove the [codes](https://github.com/greyli/flask-ckeditor/commit/810667cdd9ce1d4120650fe8c3db7a444d716739)...

You can try to make the PyPI description cool again :)

**Comment by rpmzandwijk** [comment]
Okay, I'll look to find out what's going on. If it is fixed, re-release 0.4.4 to PyPi (if that is possible at all)?

**Comment by greyli** [comment]
AFAIK PyPI doesn't allow re-upload package, you may need to make a new release(e.g. 0.4.4.1),

**Comment by rpmzandwijk** [comment]
Could you add me to the project in TestPyPi as well? I want to upload the new package to TestPyPi first to make sure it is correct.

**Comment by greyli** [comment]
I think the TestPyPI is a separate instance of PyPI, you can just create a new account and publish the package with a new name to test. I never use it before...

**Comment by rpmzandwijk** [comment]
I did just that.

You _did_ use it before: https://test.pypi.org/project/Flask-CKEditor/.  ;-)

**Comment by rpmzandwijk** [comment]
New version pushed: 0.4.4.1.

**Comment by greyli** [comment]
Great! (I totally forgot my TestPyPI account :/)
