### ISSUE TITLE
Loading an editor with pre seeded data

### ISSUE THREAD

**Issue by febin-george** [greyli/flask-ckeditor#4]
`{{ ckeditor.create() }}` returns an editor. Is it possible to return an editor with some data in it ?
Something like, `ckeditor.create(value="This text is prewritten")` should open up the editor with that text already written into it.

**Comment by greyli** [comment]
Sure, I will add it in the next release. But for now, you can achieve it by creating the CKEditor textarea manually:
```html
<textarea class="ckeditor" id="ckeditor" name="ckeditor">This text is prewritten</textarea>
```

**Comment by greyli** [comment]
Version 0.3.3 released! 

Please update with `$ pip install -U flask-ckeditor`.

**Comment by febin-george** [comment]
Great! Thank you very much for the quick response.
