### ISSUE TITLE
Hyperlink is not clickable in the `readonly` mode

### ISSUE THREAD

**Issue by holmessherlock** [greyli/flask-ckeditor#44]
In my app, I needed to load `CKEditor` in the `readonly` mode (like an HTML `<textarea>` tag) just to render the HTML content, while disallowing the user to make any changes. Unfortunately, though the hyperlinks get correctly rendered, those can't be clicked anymore. If the mouse hovers over the linked word, the link is displayed in the browser's status bar, as expected. But, neither clicking the word triggers the link, nor right-clicking the word brings up the context menu. Any idea how to get around this issue?

**Comment by greyli** [comment]
I have no experience with this. Please use [ckeditor/ckeditor4](https://github.com/ckeditor/ckeditor4/issues) to report issues about the CKEditor itself, this project is just a thin wrapper for CKEditor.
