### ISSUE TITLE
CKeditor License

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [greyli/flask-ckeditor#45]
I have the impression from here [https://ckeditor.com/pricing/](https://ckeditor.com/pricing/) that CKEditor is not completely free. So, using this extention is also not completely free. Should we include that somewhere in the README as the project currently holds an MIT license

**Comment by greyli** [comment]
Sorry for the late response. I think we are using the [open source version](https://github.com/ckeditor/ckeditor4) of CKEditor 4, it's licensed with GPL/LGPL/MPL, and [this license page](https://ckeditor.com/legal/ckeditor-oss-license/) explains the detail:

> CKEditor 4 is licensed under the terms of any of the following licenses at your choice:
>
> - GNU General Public License Version 2 or later
> - GNU Lesser General Public License Version 2.1 or later
> - Mozilla Public License Version 1.1 or later
>
> You are not required to, but if you want to explicitly declare the license you have chosen to be bound to when using, reproducing, modifying and distributing this software, just include a text file titled "legal.txt" in your version of this software, indicating your license choice. In any case, your choice will not restrict any recipient of your version of this software to use, reproduce, modify and distribute this software under any of the above licenses.

**Comment by Abdur-rahmaanJ** [comment]
Cool, thanks for clarification!
