### ISSUE TITLE
Custom_url Only Loads part of resource ?

### ISSUE THREAD

**Issue by LRENZ** [greyli/flask-ckeditor#7]
Hi, I download my  Customs CKEditor build resource  ,and Use "Custom_url" to import , but only "/static/ckeditor/ckeditor.js"
"http://127.0.0.1:5000/static/ckeditor/config.js?t=I3I8"
can be rendered in the index.html.

Here is my Template:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask-CKEditor Demo</title>
    {{ ckeditor.load(custom_url=url_for('static', filename='ckeditor/ckeditor.js')) }}
</head>

body:
	{{ ckeditor.config(name='body', custom_config="uiColor: '#9AB8F3'") }}

**Comment by greyli** [comment]
The template code seems correct. What's the problem?

**Comment by LRENZ** [comment]
Sorry to reply so late, I fix that issue by add a new files, It looks like:
<title>Flask-CKEditor Demo</title> {{ ckeditor.load(custom_url=url_for('static', filename='lib/ckeditor/ckeditor.js')) }}
I don't Know why,but it works. Thank you Very much for you patient help. 
And I notice that the new version has released and I am trying to integrate the new flask-ckeditor version(image upload) with flask-admin.
Anyway, Thanks for your awesome work

**Comment by greyli** [comment]
You are welcome :)
