### ISSUE TITLE
Image upload button didn`t show up

### ISSUE THREAD

**Issue by ivymichael** [greyli/flask-ckeditor#9]
Hi Li,

Pretty enjoyed the extension you made. Thank you very much!
Here`s one issue that inside the image property window, only **_Image Information_** and **_Link_** button are showed up, however, the **_Upload_** button is mis-rendered.

In rendered html source code page, inside the CKEditor script :
/tech is my blueprint prefix.

```
<script type="text/javascript">
  CKEDITOR.replace( "Content", {
  language: "",
  height: 0,
  width: 0,
  //toolbarCanCollapse: true,
  codeSnippet_theme: "monokai_sublime",
  imageUploadUrl: "/tech/upload",
  filebrowserUploadUrl: "/tech/upload",
  filebrowserBrowseUrl: "",
   extraPlugins: "filebrowser,filebrowser",
   });
  </script>
```
Noticed that the filebrowser string has been generated twice comparing with the project standard example I ran early, is this the problem? Any possible reason?

For whole application I have config.py, the CKEditor related :
```
class Config(object):
    CKEDITOR_FILE_UPLOADER = 'Technical.upload'
    CKEDITOR_SERVE_LOCAL = True
```

For blueprint Technical/routes.py, I basically follow instruction:

```
@mod.route('/files/<path:filename>')
def uploaded_files(filename):
    path = '/var/www/FlaskApp/FlaskApp/static/post_pics'
    return send_from_directory(path, filename)


@mod.route('/upload', methods=['POST'])
def upload():
    f = request.files.get('Technical.upload')
    extension = f.filename.split('.')[1].lower()
    if extension not in ['jpg', 'gif', 'png', 'jpeg']:
        return upload_fail(message='Image Only')
    f.save(os.path.join('/var/www/FlaskApp/FlaskApp/static/post_pics', f.filename))
    url = url_for('Technical.uploaded_files', filename=f.filename)
    return upload_success(url=url)
```
BTW, Is this correct?
`f = request.files.get('Technical.upload')`
or should I remove blueprint prefix 'Technical.'?
Thanks in advance.

**Comment by greyli** [comment]
> BTW, Is this correct? `f = request.files.get('Technical.upload')`

The input name must be `upload` (i.e. `f = request.files.get('upload')`), it's defined by CKEditor, sorry for not clarify it in README.

>  the Upload button is mis-rendered.

Could you provide the HTML template file?

**Comment by ivymichael** [comment]
Thanks for the quick reply.
Here is file link:
layout:
[](url)https://gist.github.com/ivymichael/e27ecf535068f3bf73dacc849dab0b61
create_post.html:
[](url)https://gist.github.com/ivymichael/ce098e39ac356e2f251a586b0cdb62e4

**Comment by ivymichael** [comment]
Hi,
Problem solved!
I made a mistake that in my models.py, the post main body name is defined as 'content',
however I used 'Content' in CKEditor.config(), that causes the duplicates of string 'filebrowser' somehow.

Sorry to bother, thank you!

**Comment by greyli** [comment]
It's my pleasure :)
